pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    // Make sure your branch name is correct!
                    checkout scmGit(
                        branches: [[name: 'moji/branch/terraform']],
                        extensions: [],
                        userRemoteConfigs: [[url: 'https://github.com/MojiJokar/Ds_Devops_project_mine.git']]
                    )
                }
            }
        }
        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }
        // Add more stages as needed, always using dir('terraform') for commands in that folder
    }
}
